add quickbar proxy
serlo/serlo.org-cloudflare-worker pull request #237
Opened 2021-09-20 11:09 UTC by elbotho

closes #235

2021-09-20 12:45 UTC, elbotho commented on src/quickbarProxy.ts
> +  if (url.pathname !== '/api/stats/quickbar.json') return null
only needs to support `DE` for now, that's why I don't check the subdomain here.

2021-09-21 07:48 UTC, kulla requested changes

2021-09-21 07:48 UTC, kulla commented on __tests__/quickbarProxy.ts
> +/**
rename to `__tests__/quickbar-proxy.ts`

2021-09-21 07:48 UTC, kulla commented on __tests__/quickbarProxy.ts
> +    const response = await requestJson('/api/stats/quickbar.json')
```suggestion
   const env = currentTestEnvironment()
    const response = await env.fetch({ pathname: '/api/stats/quickbar.json' })
```

2021-09-21 07:48 UTC, kulla commented on __tests__/quickbarProxy.ts
> +  }
Can be merged together in one function like `setupQuickbarServer()`.

2021-09-21 07:48 UTC, kulla commented on src/quickbarProxy.ts
> +
```suggestion
if (!isInstance(url.subdomain)) return null
```

2021-09-21 07:48 UTC, kulla commented on src/quickbarProxy.ts
> +    // this should be reported, right?
See https://github.com/serlo/serlo.org-cloudflare-worker/blob/main/src/metadata-api.ts for a good example. You may need to add a `SentryReporter.captureException()` method like https://github.com/serlo/serlo.org-cloudflare-worker/blob/main/src/utils/sentry.ts#L44-L46 See https://github.com/robertcepa/toucan-js#features for the methods the object returned by `getToucan()` supports..

2021-09-21 17:05 UTC, kulla approved these changes

2021-09-21 17:07 UTC, merged