refactor(legal): move legal pages to frontend, simplify
serlo/serlo.org-cloudflare-worker pull request #590
Opened 2023-11-15 15:27 UTC by elbotho

2023-11-17 10:29 UTC, elbotho commented on src/frontend-proxy.ts
> +    new Request(backendUrl.toString(), { headers: request.headers }),
Not sure about this one. Is it enough to pass the headers?

2023-11-20 16:15 UTC, kulla requested changes

2023-11-20 16:15 UTC, kulla commented on __tests__/utils.tsx
> +test('HtmlResponse', async () => {
Follow-Up: Should not be needed... I guess this can be deleted as well...

2023-11-20 16:15 UTC, kulla commented on jest.setup.ts
> +  globalThis.cryptoDigest = (encoding: string, message: Uint8Array) => {
I think this should be `crypo.subtle` -> See https://developers.cloudflare.com/workers/runtime-apis/web-crypto#subtlecrypto-methods

2023-11-20 16:15 UTC, kulla commented on jest.setup.ts
> +  var cryptoDigest: (encoding: string, message: Uint8Array) => Promise<Buffer>
```suggestion
```

There is no global `cryptoDigest()` in CF worker -> So this will not work...

2023-11-20 16:38 UTC, kulla approved these changes
Okay, I have fixed all leftover issues. It should be save to deploy...

2023-11-20 16:39 UTC, kulla commented
> before the unexpected (probably unrelated) type problem this was a really clean PR 😬 @kulla did you encounter problems with the `RequestInit` or fetch types before?

This is due to https://github.com/cloudflare/workerd/issues/1298 I have fixed the type errors...

2023-11-20 16:47 UTC, merged

2023-11-21 09:40 UTC, elbotho commented on __tests__/__utils__/test-environment.ts
> +    return new Request<unknown, CfProperties>(this.createUrl(spec), init)
nice!