feat: Support redirects for course pages
serlo/serlo.org-cloudflare-worker pull request #796
Opened 2024-06-12 15:03 UTC by kulla

Fixes #795 

Blocker: This PR needs https://github.com/serlo/api.serlo.org/pull/1579

2024-06-12 16:07 UTC, elbotho commented on __tests__/__utils__/services/database.ts
> +      '(?<subject>[^/]+/)?(?<id>\\d+)(?<coursePageId>/[a-z0-9-]+)?/(?<title>[^/]*)$',
```suggestion
      '(?<subject>[^/]+/)?(?<id>\\d+)(?<coursePageId>/[0-9a-f]+)?/(?<title>[^/]*)$',
```
(see slack)

2024-06-12 16:12 UTC, elbotho requested changes
short regex feedback, no proper review yet

2024-06-12 16:12 UTC, elbotho commented on __tests__/current-alias-redirects.ts
> +      pathname: '/math/42/page2/bar',
```suggestion
      pathname: '/math/42/1a2b3c4d/bar',
```
(optional) would be more realistic

2024-06-12 16:12 UTC, elbotho commented on src/current-alias-redirects.ts
> +    /^\/(?<instance>[a-z]{2}\/)?(?<subject>[a-z]+\/)?(?<id>\d+)\/(?<coursePageId>[a-z0-9-]+)\/(?<title>[^/]*)$/,
```suggestion
    /^\/(?<instance>[a-z]{2}\/)?(?<subject>[a-z]+\/)?(?<id>\d+)\/(?<coursePageId>[0-9a-f]+)\/(?<title>[^/]*)$/,
```

2024-06-14 12:37 UTC, kulla commented
> short regex feedback, no proper review yet

@elbotho Fixed in https://github.com/serlo/cloudflare-worker/pull/796/commits/1bd81acb4ef34002294fc2747cf9f3cf54836f9b

2024-06-19 13:21 UTC, AndreasHuber commented on src/current-alias-redirects.ts
> +// Copied from https://github.com/serlo/api.serlo.org/blob/ce94045b513e59da1ddd191b498fe01f6ff6aa0a/packages/server/src/schema/uuid/abstract-uuid/resolvers.ts#L685-L703
Why? Can't you put it in a separate file to be used by both?

2024-06-19 13:32 UTC, elbotho commented
@kulla what would happen if I request an old `coursePage` path like `/51553` or `/mathe/51553/linearfaktordarstellung-1-3`? Do they get redirected to the new format now?

2024-06-19 15:46 UTC, kulla commented
> @kulla what would happen if I request an old `coursePage` path like `/51553` or `/mathe/51553/linearfaktordarstellung-1-3`? Do they get redirected to the new format now?

Should happen after the API merge

2024-06-19 16:37 UTC, elbotho approved these changes
I will try this in staging and address improvements / fixes later

2024-06-19 16:40 UTC, merged