No redirect for /spenden
serlo/serlo.org-cloudflare-worker pull request #87
Opened 2020-12-02 09:50 UTC by kulla

Resolves the bug that `/spenden` is redirecting to `/21565/spenden` because there is still an old page. Due to the new alias system a redirect would be triggered. It also implements the logic that `/spenden` is treated like `/search` (where the cookie determines the backend).

2020-12-02 09:52 UTC, kulla commented on __tests__/__utils__/index.ts
> +}
I noticed that when a test suite like `maintenance.ts` imports from `frontend-proxy.ts` the tests from `frontend-proxy.ts` are executed twice. I'll do a follow up PR which cleans up the utility functions.

2020-12-02 09:53 UTC, kulla commented on __tests__/frontend-proxy.ts
> +    })
Works now: https://frontend.serlo.org/de/spenden

2020-12-07 15:14 UTC, CarolinJaser requested changes
Thanks Kulla, I only have one small comment.

2020-12-07 19:11 UTC, kulla commented on src/frontend-proxy.ts
> +export const specialPaths = ['/', '/search', '/spenden']
Fixed in https://github.com/serlo/serlo.org-cloudflare-worker/pull/98

2020-12-07 19:15 UTC, kulla commented
@kulla Ready for merge, have implemented your code suggestion in a new PR. Feel free to merge :smile:

2020-12-08 14:44 UTC, CarolinJaser commented on src/frontend-proxy.ts
> +export const specialPaths = ['/', '/search', '/spenden']
Ok, great, thanks!

2020-12-08 14:45 UTC, CarolinJaser approved these changes

2020-12-09 11:51 UTC, merged